# name: Deploy API to Azure Container Apps

# on:
#   push:
#     paths:
#       - "api/**"
#       - ".github/workflows/api-deploy.yml"
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Azure Login
#         uses: azure/login@v2
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - name: Build and Deploy to Azure Container Apps
#         uses: Azure/container-apps-deploy-action@v2
#         with:
#           appSourcePath: ./api
#           dockerfilePath: ./api/Dockerfile
#           resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
#           containerAppName: ${{ secrets.AZURE_CONTAINERAPP_NAME }}
#           environment: ${{ secrets.AZURE_CONTAINERAPPS_ENVIRONMENT }}
#           location: ${{ secrets.AZURE_LOCATION }}
#           imageName: mean-api:latest
