name: Deploy UI to Azure Static Web Apps - Stage Environment

on:
  push:
    branches:
      - main # Triggers production deployment for UI

jobs:
  build_and_deploy_staging:
    runs-on: ubuntu-latest
    name: Build and Deploy to Staging
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client

      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            return await coredemo.getIDToken()
          result-encoding: string

      - name: Build And Deploy to Staging
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_RIVER_013F9EC0F }}
          action: "upload"
          # Repository/Build Configurations
          app_location: "./ui" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist/ui/browser" # Built app content directory
          github_id_token: ${{ steps.idtoken.outputs.result }}
